apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: spring-app:1.3
          # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster